### PR TITLE
Get IP from headers or request

### PR DESCRIPTION
**Pull request by 1kamma**
- added the function GetIPFromHeader that gets the gin.content and returns the ip, if there was x-real-ip header.

### CODE REVIEW

**Comment by jantari** [comment]
Thanks for the PR.

Gins [Context.ClientIP()](https://pkg.go.dev/github.com/gin-gonic/gin#Context.ClientIP) function will already read and return `X-Real-Ip` *IF* the remote address is a trusted proxy. Rewinged currently does not allow you to set a trusted proxy, it's hardcoded to `nil`:

https://github.com/jantari/rewinged/blob/9a619c5d27c67469a27259535d95bd8ff001c6d6/main.go#L148

However, I believe that would be the correct solution rather than re-implementing the feature in a broken way (you *cannot* trust client-controllable headers like X-Real-IP unless you know you get them from your own, trusted proxy).

Do you think you can update the PR?

**Comment by 1kamma** [comment]
@jantari updated

**Review by 1kamma — COMMENTED** [review]
added what you suggested

**Comment by jantari** [comment]
Thanks! I took a quick look, will go through it again when I have some more time next week and then merge.

**Comment by jantari** [comment]
Thanks a lot for the contribution. I have made some edits myself in https://github.com/jantari/rewinged/pull/8/commits/d214ad9c4d1f3cb1b860fa0ab03c499c7b20da9f, but now this will ship in the next release.

**Pull request merged**
